"""
Defines the discrete action space for the traffic signal agent.

Design decision: rather than an abstract "keep/switch/extend" action
set, the agent directly selects which GREEN phase should be active.
We discover available green phases from the traffic light's own
program (auto-generated by netconvert in Phase 3) instead of
hardcoding phase indices, so this stays correct if the network's
signal program ever changes.

Switching between two different green phases requires passing through
a mandatory yellow transition -- this module also handles finding the
correct yellow phase for a given green phase.
"""

import traci


def get_green_phases(tls_id: str) -> list:
    """
    Returns the list of phase INDICES in the traffic light's program
    that are "green" phases (i.e. at least one lane gets a green
    signal, and it is not a yellow transition phase).

    netconvert's default programs alternate green -> yellow -> green
    -> yellow ... so we identify green phases as any phase whose
    state string contains no 'y' (yellow) character.
    """
    logic = traci.trafficlight.getAllProgramLogics(tls_id)[0]
    green_indices = []
    for i, phase in enumerate(logic.phases):
        if "y" not in phase.state.lower():
            green_indices.append(i)
    return green_indices


def get_yellow_phase_for(tls_id: str, green_phase_index: int) -> int | None:
    """
    Given a green phase index, returns the index of the yellow phase
    that should play immediately after it, following netconvert's
    convention of placing the yellow transition right after its
    corresponding green phase in the program list. Returns None if no
    such yellow phase exists (shouldn't normally happen with
    netconvert-generated programs, but guarded defensively).
    """
    logic = traci.trafficlight.getAllProgramLogics(tls_id)[0]
    num_phases = len(logic.phases)
    next_index = (green_phase_index + 1) % num_phases
    next_state = logic.phases[next_index].state.lower()
    if "y" in next_state:
        return next_index
    return None


class ActionSpace:
    """
    Thin wrapper describing the discrete action space: one action per
    available green phase. action_index -> actual TraCI phase index
    is resolved via self.green_phases[action_index].
    """

    def __init__(self, tls_id: str):
        self.tls_id = tls_id
        self.green_phases = get_green_phases(tls_id)
        self.n = len(self.green_phases)

        if self.n == 0:
            raise ValueError(
                f"No green phases found for traffic light '{tls_id}'. "
                "Check the network's auto-generated signal program."
            )

    def action_to_phase_index(self, action: int) -> int:
        """Maps an agent action (0..n-1) to the actual TraCI phase index."""
        return self.green_phases[action]